package com.nightbeam.tbos.entity;

/*
 * Generated by tools/models/legacy_entity_port.py from
 * shared/common/src/main/java/com/nightbeam/tbos/entity/MinotaurEntity.java.
 * Edit the shared class and re-run the script; do not hand-patch this copy.
 */

import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.syncher.EntityDataAccessor;
import net.minecraft.network.syncher.EntityDataSerializers;
import net.minecraft.network.syncher.SynchedEntityData;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.goal.FloatGoal;
import net.minecraft.world.entity.ai.goal.LookAtPlayerGoal;
import net.minecraft.world.entity.ai.goal.MeleeAttackGoal;
import net.minecraft.world.entity.ai.goal.RandomLookAroundGoal;
import net.minecraft.world.entity.ai.goal.WaterAvoidingRandomStrollGoal;
import net.minecraft.world.entity.ai.goal.target.HurtByTargetGoal;
import net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal;
import net.minecraft.world.entity.monster.Monster;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;

/**
 * A horned Archive bruiser that patrols the procedural chambers.
 *
 * <p>Where the theme exclusives skirmish, the minotaur commits: it stops, coils
 * for {@link Phase#WINDUP}, and drops an overhead slam that damages and throws
 * everything inside {@link #SLAM_RADIUS}. The wind-up is deliberately long
 * enough to walk out of, which is what keeps a chamber spawn fair — the danger
 * is being cornered by one, not being hit by one.
 */
public final class MinotaurEntity extends Monster {
    private static final EntityDataAccessor<Byte> PHASE =
            SynchedEntityData.defineId(MinotaurEntity.class, EntityDataSerializers.BYTE);
    private static final EntityDataAccessor<Integer> PHASE_TICKS =
            SynchedEntityData.defineId(MinotaurEntity.class, EntityDataSerializers.INT);

    /** Reach of the slam. Comfortably inside the smallest authored room. */
    public static final double SLAM_RADIUS = 3.5D;

    private static final double SLAM_RADIUS_SQR = SLAM_RADIUS * SLAM_RADIUS;
    private static final float SLAM_DAMAGE = 8.0F;
    private static final double SLAM_KNOCKBACK = 0.62D;
    private static final int WINDUP_TICKS = 22;
    private static final int SLAM_TICKS = 18;

    /** The blow lands early in the slam so the recovery reads as follow-through. */
    private static final int SLAM_IMPACT_TICK = 5;

    private static final int SLAM_COOLDOWN = 110;
    private static final int INITIAL_SLAM_COOLDOWN = 50;

    private int slamCooldown = INITIAL_SLAM_COOLDOWN;

    public MinotaurEntity(EntityType<? extends MinotaurEntity> entityType, Level level) {
        super(entityType, level);
        this.xpReward = 18;
    }

    @Override
    protected void registerGoals() {
        goalSelector.addGoal(1, new FloatGoal(this));
        goalSelector.addGoal(2, new MeleeAttackGoal(this, 1.0D, false));
        goalSelector.addGoal(3, new WaterAvoidingRandomStrollGoal(this, 0.7D));
        goalSelector.addGoal(4, new LookAtPlayerGoal(this, Player.class, 14.0F));
        goalSelector.addGoal(5, new RandomLookAroundGoal(this));
        targetSelector.addGoal(1, new HurtByTargetGoal(this).setAlertOthers());
        targetSelector.addGoal(2, new NearestAttackableTargetGoal<>(this, Player.class, true));
    }

    @Override
    protected void defineSynchedData() {
        super.defineSynchedData();
        this.entityData.define(PHASE, (byte) Phase.IDLE.ordinal());
        this.entityData.define(PHASE_TICKS, 0);
    }

    @Override
    protected void customServerAiStep() {
        super.customServerAiStep();
        if (!(level() instanceof ServerLevel level)) {
            return;
        }

        Phase phase = getPhase();
        if (phase == Phase.IDLE) {
            if (slamCooldown > 0) {
                slamCooldown--;
                return;
            }
            LivingEntity target = getTarget();
            if (target != null && target.isAlive() && distanceToSqr(target) <= SLAM_RADIUS_SQR * 1.6D) {
                beginPhase(Phase.WINDUP);
                playSound(SoundEvents.RAVAGER_ROAR, 1.1F, 0.8F);
            }
            return;
        }

        int elapsed = getPhaseTicks() + 1;
        setPhaseTicks(elapsed);
        // Planted for the whole commitment: a minotaur that slid through its own
        // wind-up would land the slam from outside the tell.
        setDeltaMovement(getDeltaMovement().multiply(0.2D, 1.0D, 0.2D));

        switch (phase) {
            case WINDUP -> {
                if (elapsed >= WINDUP_TICKS) {
                    beginPhase(Phase.SLAM);
                }
            }
            case SLAM -> {
                if (elapsed == SLAM_IMPACT_TICK) {
                    slam(level);
                }
                if (elapsed >= SLAM_TICKS) {
                    slamCooldown = SLAM_COOLDOWN;
                    beginPhase(Phase.IDLE);
                }
            }
            default -> beginPhase(Phase.IDLE);
        }
    }

    private void slam(ServerLevel level) {
        for (LivingEntity victim :
                level.getEntitiesOfClass(LivingEntity.class, getBoundingBox().inflate(SLAM_RADIUS))) {
            if (victim == this || !victim.isAlive() || distanceToSqr(victim) > SLAM_RADIUS_SQR) {
                continue;
            }
            victim.hurt(damageSources().mobAttack(this), SLAM_DAMAGE);
            Vec3 away = victim.position().subtract(position());
            Vec3 flat = new Vec3(away.x, 0.0D, away.z);
            if (flat.lengthSqr() > 1.0E-4D) {
                Vec3 push = flat.normalize().scale(SLAM_KNOCKBACK);
                victim.push(push.x, 0.36D, push.z);
                victim.hurtMarked = true;
            }
        }

        level.sendParticles(
                ParticleTypes.CLOUD, getX(), getY() + 0.1D, getZ(), 30, 1.2D, 0.1D, 1.2D, 0.06D);
        level.playSound(
                null, getX(), getY(), getZ(),
                SoundEvents.RAVAGER_ATTACK, SoundSource.HOSTILE, 1.3F, 0.7F);
    }

    @Override
    public void readAdditionalSaveData(CompoundTag input) {
        super.readAdditionalSaveData(input);
        // A slam caught mid-swing must restart rather than resolve on load.
        slamCooldown = INITIAL_SLAM_COOLDOWN;
        beginPhase(Phase.IDLE);
    }

    @Override
    protected SoundEvent getAmbientSound() {
        return SoundEvents.RAVAGER_AMBIENT;
    }

    @Override
    protected SoundEvent getHurtSound(DamageSource damageSource) {
        return SoundEvents.RAVAGER_HURT;
    }

    @Override
    protected SoundEvent getDeathSound() {
        return SoundEvents.RAVAGER_DEATH;
    }

    public Phase getPhase() {
        byte ordinal = entityData.get(PHASE);
        Phase[] values = Phase.values();
        return ordinal >= 0 && ordinal < values.length ? values[ordinal] : Phase.IDLE;
    }

    public int getPhaseTicks() {
        return entityData.get(PHASE_TICKS);
    }

    /** Zero at the start of the current phase, one at its end. */
    public float getPhaseProgress(float partialTick) {
        int span = getPhase().durationTicks();
        if (span <= 0) {
            return 0.0F;
        }
        return Mth.clamp((getPhaseTicks() + partialTick) / span, 0.0F, 1.0F);
    }

    private void setPhaseTicks(int ticks) {
        entityData.set(PHASE_TICKS, ticks);
    }

    private void beginPhase(Phase phase) {
        entityData.set(PHASE, (byte) phase.ordinal());
        setPhaseTicks(0);
    }

    /** The slam beats, in the order the model animates them. */
    public enum Phase {
        IDLE(0),
        WINDUP(WINDUP_TICKS),
        SLAM(SLAM_TICKS);

        private final int durationTicks;

        Phase(int durationTicks) {
            this.durationTicks = durationTicks;
        }

        public int durationTicks() {
            return durationTicks;
        }
    }
}
