package com.nightbeam.tbos.client.render;

import com.nightbeam.tbos.Yesterglass;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.nightbeam.tbos.entity.MinotaurEntity;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * A horned Archive bruiser that coils its whole body into an overhead warhammer slam.
 *
 * <p>Generated by {@code tools/models/bb_to_model.py} from
 * {@code tools/models/raw/minotaur.java}. The mesh is a verbatim Blockbench
 * export -- edit the {@code .bbmodel} and re-run the script rather than
 * hand-patching {@code createBodyLayer}. Only the animation is authored, and it
 * lives once in {@code tools/models/anim/minotaur.frag} for every version.
 */
public final class MinotaurModel extends EntityModel<MinotaurEntity> {
    public static final ModelLayerLocation MODEL_LAYER = new ModelLayerLocation(
            new ResourceLocation(Yesterglass.MOD_ID, "minotaur"),
            "main");

    private final ModelPart rootPart;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart armorRightArm;
    private final ModelPart rightLeg;
    private final ModelPart head;
    private final ModelPart torso;
    private final ModelPart leftLeg;
    private final ModelPart leftArm;

    public MinotaurModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        rootPart = root;
        body = root.getChild("body");
        rightArm = body.getChild("rightArm");
        armorRightArm = rightArm.getChild("armorRightArm");
        rightLeg = body.getChild("rightLeg");
        head = body.getChild("head");
        torso = body.getChild("torso");
        leftLeg = body.getChild("leftLeg");
        leftArm = body.getChild("leftArm");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition body = partdefinition.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.1745F, 0.0F, 0.0F));

        PartDefinition rightArm = body.addOrReplaceChild("rightArm", CubeListBuilder.create(), PartPose.offset(-9.0F, -16.0F, 2.0F));

        PartDefinition armorRightArm = rightArm.addOrReplaceChild("armorRightArm", CubeListBuilder.create().texOffs(96, 22).addBox(-6.25F, -13.5F, -3.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.55F))
        .texOffs(44, 89).addBox(-8.25F, -15.5F, -4.0F, 8.0F, 14.0F, 10.0F, new CubeDeformation(0.55F)), PartPose.offsetAndRotation(-3.5298F, 9.9388F, -4.5752F, -0.4363F, 0.5672F, 0.0F));

        PartDefinition itemAnchor = armorRightArm.addOrReplaceChild("itemAnchor", CubeListBuilder.create(), PartPose.offsetAndRotation(0.75F, 14.5F, 1.0F, 0.1201F, -0.4205F, -0.2875F));

        PartDefinition itemBone = itemAnchor.addOrReplaceChild("itemBone", CubeListBuilder.create().texOffs(-12, 41).addBox(-13.0F, -2.0F, -1.0F, 58.0F, 2.0F, 2.0F, new CubeDeformation(0.5F))
        .texOffs(128, 39).addBox(31.0F, -2.0F, -1.0F, 6.0F, 2.0F, 2.0F, new CubeDeformation(1.0F))
        .texOffs(56, 75).addBox(43.0F, -2.0F, -1.0F, 2.0F, 2.0F, 2.0F, new CubeDeformation(1.0F))
        .texOffs(0, 0).addBox(46.4F, -10.0F, -13.0F, 16.0F, 16.0F, 25.0F, new CubeDeformation(0.5F))
        .texOffs(0, 75).addBox(45.4F, -11.0F, -15.0F, 18.0F, 18.0F, 4.0F, new CubeDeformation(0.0F))
        .texOffs(82, 0).addBox(45.4F, -11.0F, 9.0F, 18.0F, 18.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offset(3.2869F, 1.0706F, -0.1874F));

        PartDefinition bone = armorRightArm.addOrReplaceChild("bone", CubeListBuilder.create(), PartPose.offset(5.75F, 25.5F, -1.0F));

        PartDefinition bone_r1 = bone.addOrReplaceChild("bone_r1", CubeListBuilder.create().texOffs(0, 97).addBox(-4.0F, 0.0F, -4.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.55F)), PartPose.offsetAndRotation(-8.0F, -26.0F, 2.0F, 0.2278F, -1.247F, -0.3348F));

        PartDefinition rightLeg = body.addOrReplaceChild("rightLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(-7.0F, 2.0F, 2.0F, -0.2722F, 0.5572F, 0.0951F));

        PartDefinition armorRightBoot = rightLeg.addOrReplaceChild("armorRightBoot", CubeListBuilder.create(), PartPose.offset(-2.0F, -5.0F, -2.0F));

        PartDefinition armorRightLeg = rightLeg.addOrReplaceChild("armorRightLeg", CubeListBuilder.create().texOffs(32, 113).addBox(-2.0F, 5.0F, -2.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.8F))
        .texOffs(128, 117).addBox(-1.0F, 15.0F, -4.0F, 6.0F, 6.0F, 1.0F, new CubeDeformation(0.6F)), PartPose.offset(-2.0F, -5.0F, -2.0F));

        PartDefinition bone2 = armorRightLeg.addOrReplaceChild("bone2", CubeListBuilder.create(), PartPose.offset(2.0F, 18.8584F, -1.5951F));

        PartDefinition bone2_r1 = bone2.addOrReplaceChild("bone2_r1", CubeListBuilder.create().texOffs(0, 119).addBox(-4.0F, 10.0F, -2.0F, 8.0F, 2.0F, 8.0F, new CubeDeformation(1.0F))
        .texOffs(112, 44).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 8.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(0.0F, -0.8584F, 1.5951F, 0.4363F, 0.0F, 0.0F));

        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 45).addBox(-8.0F, -14.0F, -8.0F, 16.0F, 14.0F, 16.0F, new CubeDeformation(0.0F))
        .texOffs(128, 27).addBox(-16.0F, -11.0F, -1.0F, 13.0F, 3.0F, 3.0F, new CubeDeformation(0.5F))
        .texOffs(82, 22).addBox(13.0F, -19.0F, -1.0F, 3.0F, 11.0F, 3.0F, new CubeDeformation(0.4F))
        .texOffs(128, 33).addBox(3.0F, -11.0F, -1.0F, 13.0F, 3.0F, 3.0F, new CubeDeformation(0.5F))
        .texOffs(44, 75).addBox(-16.0F, -19.0F, -1.0F, 3.0F, 11.0F, 3.0F, new CubeDeformation(0.4F))
        .texOffs(128, 10).addBox(-3.5F, -14.0F, -12.0F, 7.0F, 12.0F, 5.0F, new CubeDeformation(0.2F)), PartPose.offset(0.0F, -19.0F, 2.0F));

        PartDefinition armorHead = head.addOrReplaceChild("armorHead", CubeListBuilder.create(), PartPose.offset(0.0F, 1.0F, -2.0F));

        PartDefinition torso = body.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(64, 45).addBox(-8.0F, -6.8F, -2.0F, 16.0F, 20.0F, 8.0F, new CubeDeformation(0.6F))
        .texOffs(64, 73).addBox(-8.0F, 8.2F, -3.0F, 16.0F, 6.0F, 10.0F, new CubeDeformation(0.65F))
        .texOffs(128, 110).addBox(-3.0F, 6.2F, -4.0F, 6.0F, 4.0F, 3.0F, new CubeDeformation(0.6F)), PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition leftLeg = body.addOrReplaceChild("leftLeg", CubeListBuilder.create(), PartPose.offsetAndRotation(7.0F, 2.0F, 2.0F, -0.2722F, -0.5572F, -0.0951F));

        PartDefinition armorLeftBoot = leftLeg.addOrReplaceChild("armorLeftBoot", CubeListBuilder.create(), PartPose.offset(2.0F, -5.0F, -2.0F));

        PartDefinition armorLeftLeg = leftLeg.addOrReplaceChild("armorLeftLeg", CubeListBuilder.create().texOffs(32, 113).mirror().addBox(-6.0F, 5.0F, -2.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.8F)).mirror(false)
        .texOffs(128, 117).mirror().addBox(-5.0F, 15.0F, -4.0F, 6.0F, 6.0F, 1.0F, new CubeDeformation(0.6F)).mirror(false), PartPose.offset(2.0F, -5.0F, -2.0F));

        PartDefinition bone3 = armorLeftLeg.addOrReplaceChild("bone3", CubeListBuilder.create(), PartPose.offset(-2.0F, 18.8584F, 5.4049F));

        PartDefinition bone3_r1 = bone3.addOrReplaceChild("bone3_r1", CubeListBuilder.create().texOffs(0, 119).mirror().addBox(-4.0F, 10.0F, -2.0F, 8.0F, 2.0F, 8.0F, new CubeDeformation(1.0F)).mirror(false)
        .texOffs(112, 44).mirror().addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 8.0F, new CubeDeformation(0.6F)).mirror(false), PartPose.offsetAndRotation(0.0F, -0.8584F, -5.4049F, 0.4363F, 0.0F, 0.0F));

        PartDefinition leftArm = body.addOrReplaceChild("leftArm", CubeListBuilder.create(), PartPose.offset(9.0F, -16.0F, 2.0F));

        PartDefinition armorLeftArm = leftArm.addOrReplaceChild("armorLeftArm", CubeListBuilder.create().texOffs(96, 22).mirror().addBox(-1.0F, -3.0F, -2.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.55F)).mirror(false)
        .texOffs(44, 89).mirror().addBox(1.0F, -5.0F, -3.0F, 8.0F, 14.0F, 10.0F, new CubeDeformation(0.55F)).mirror(false), PartPose.offsetAndRotation(1.0F, 0.0F, -2.0F, -0.4363F, -0.5672F, 0.0F));

        PartDefinition bone4 = armorLeftArm.addOrReplaceChild("bone4", CubeListBuilder.create(), PartPose.offset(-5.0F, 36.0F, 0.0F));

        PartDefinition bone4_r1 = bone4.addOrReplaceChild("bone4_r1", CubeListBuilder.create().texOffs(0, 97).mirror().addBox(-4.0F, 0.0F, -4.0F, 8.0F, 14.0F, 8.0F, new CubeDeformation(0.55F)).mirror(false), PartPose.offsetAndRotation(8.0F, -26.0F, 2.0F, 0.2278F, 1.247F, 0.3348F));

        return LayerDefinition.create(meshdefinition, 256, 256);
    }

    @Override
    public void setupAnim(
            MinotaurEntity entity,
            float limbSwing,
            float limbSwingAmount,
            float ageInTicks,
            float netHeadYaw,
            float headPitch) {
        rootPart.getAllParts().forEach(ModelPart::resetPose);
        MinotaurRenderState state = new MinotaurRenderState();
        state.ageInTicks = ageInTicks;
        state.walkAnimationPos = limbSwing;
        state.walkAnimationSpeed = limbSwingAmount;
        state.yRot = netHeadYaw;
        state.xRot = headPitch;
        state.phase = entity.getPhase();
        state.phaseProgress = entity.getPhaseProgress(ageInTicks - entity.tickCount);
        state.attackTime = attackTime;
        state.hurtTime = Mth.clamp(entity.hurtTime / 10.0F, 0.0F, 1.0F);

        float drift = Mth.clamp(state.walkAnimationSpeed, 0.0F, 1.0F);
        float cycle = state.walkAnimationPos * 0.6F;
        float idle = Mth.sin(state.ageInTicks * 0.055F);

        head.yRot += state.yRot * (float) (Math.PI / 180.0);
        head.xRot += state.xRot * (float) (Math.PI / 180.0);

        // Heavy biped gait: long stride, and the torso counter-rotates against
        // the legs so the weight reads as bulk rather than a walking plank.
        rightLeg.xRot += Mth.cos(cycle) * 1.05F * drift;
        leftLeg.xRot += Mth.cos(cycle + (float) Math.PI) * 1.05F * drift;
        rightArm.xRot += Mth.cos(cycle + (float) Math.PI) * 0.75F * drift;
        leftArm.xRot += Mth.cos(cycle) * 0.75F * drift;
        torso.yRot += Mth.cos(cycle) * 0.09F * drift;
        body.y += Mth.abs(Mth.cos(cycle)) * 0.9F * drift;

        // Idle sway, damped out once it is actually moving.
        float settle = 1.0F - drift;
        torso.zRot += idle * 0.03F * settle;
        rightArm.zRot += idle * 0.05F * settle;
        leftArm.zRot -= idle * 0.05F * settle;
        head.zRot += idle * 0.04F * settle;

        switch (state.phase) {
            case WINDUP -> {
                // Weapon arm hauls up and back; the whole body coils away from
                // the target so the swing has somewhere to come from.
                float coil = Mth.sin(state.phaseProgress * (float) Math.PI * 0.5F);
                rightArm.xRot -= coil * 2.3F;
                rightArm.zRot -= coil * 0.5F;
                armorRightArm.xRot -= coil * 0.4F;
                torso.yRot -= coil * 0.45F;
                head.xRot -= coil * 0.25F;
                body.y += coil * 1.2F;
            }
            case SLAM -> {
                // Down and through, then a short recovery as progress runs out.
                float swing = Mth.sin(state.phaseProgress * (float) Math.PI);
                float through = state.phaseProgress;
                rightArm.xRot += (1.0F - through) * -1.4F + through * 1.1F;
                rightArm.zRot += swing * 0.35F;
                armorRightArm.xRot += swing * 0.5F;
                torso.yRot += through * 0.5F - 0.45F;
                body.y -= swing * 1.6F;
                head.xRot += swing * 0.4F;
            }
            default -> {
            }
        }

        float swipe = Mth.sin(state.attackTime * (float) Math.PI);
        rightArm.xRot -= swipe * 1.2F;
        leftArm.xRot -= swipe * 0.3F;

        if (state.hurtTime > 0.0F) {
            torso.zRot += state.hurtTime * 0.14F;
            head.zRot -= state.hurtTime * 0.1F;
        }
    }

    @Override
    public void renderToBuffer(
            PoseStack poseStack,
            VertexConsumer vertexConsumer,
            int packedLight,
            int packedOverlay,
            float red,
            float green,
            float blue,
            float alpha) {
        rootPart.render(poseStack, vertexConsumer, packedLight, packedOverlay, red, green, blue, alpha);
    }
}
