plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

def accessTransformer = resolveSharedFile('common', 'resources', 'META-INF/accesstransformer.cfg')

legacyForge {
    mcpVersion = minecraft_version
    if (accessTransformer.exists()) {
        accessTransformers = [accessTransformer.absolutePath]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    sourceSets.main.java.srcDirs.each { if (it.directory) commonJava it }
    sourceSets.main.resources.srcDirs.each { if (it.directory) commonResources it }
}
