package com.nightbeam.tbos.client.render;

import com.nightbeam.tbos.Yesterglass;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.nightbeam.tbos.entity.PhoenixGuardianEntity;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/**
 * The Last Curator: a crowned, legless sentinel whose four wing-arms fan open when it charges and snap shut when it strikes.
 *
 * <p>Generated by {@code tools/models/bb_to_model.py} from
 * {@code tools/models/raw/phoenix_guardian.java}. The mesh is a verbatim Blockbench
 * export -- edit the {@code .bbmodel} and re-run the script rather than
 * hand-patching {@code createBodyLayer}. Only the animation is authored, and it
 * lives once in {@code tools/models/anim/phoenix_guardian.frag} for every version.
 */
public final class PhoenixGuardianModel extends EntityModel<PhoenixGuardianEntity> {
    public static final ModelLayerLocation MODEL_LAYER = new ModelLayerLocation(
            ResourceLocation.fromNamespaceAndPath(Yesterglass.MOD_ID, "phoenix_guardian"),
            "main");

    private final ModelPart rootPart;
    private final ModelPart body;
    private final ModelPart torso;
    private final ModelPart bone14;
    private final ModelPart bone15;
    private final ModelPart rightArm;
    private final ModelPart bone2;
    private final ModelPart bone4;
    private final ModelPart leftArm;
    private final ModelPart bone8;
    private final ModelPart bone9;
    private final ModelPart head;
    private final ModelPart armorHead;

    public PhoenixGuardianModel(ModelPart root) {
        super(RenderType::entityCutoutNoCull);
        rootPart = root;
        body = root.getChild("body");
        torso = body.getChild("torso");
        bone14 = torso.getChild("bone14");
        bone15 = torso.getChild("bone15");
        rightArm = body.getChild("rightArm");
        bone2 = rightArm.getChild("bone2");
        bone4 = bone2.getChild("bone4");
        leftArm = body.getChild("leftArm");
        bone8 = leftArm.getChild("bone8");
        bone9 = bone8.getChild("bone9");
        head = body.getChild("head");
        armorHead = head.getChild("armorHead");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition body = partdefinition.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.offset(0.0F, 12.0F, 0.0F));

        PartDefinition torso = body.addOrReplaceChild("torso", CubeListBuilder.create(), PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition bone14 = torso.addOrReplaceChild("bone14", CubeListBuilder.create().texOffs(92, 106).addBox(-2.0F, -12.0F, -5.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F))
        .texOffs(116, 106).addBox(-2.0F, -12.0F, 3.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition torso_r1 = bone14.addOrReplaceChild("torso_r1", CubeListBuilder.create().texOffs(0, 118).addBox(-2.0F, -26.8F, 5.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(1.0F, 14.8F, -2.0F, 0.0F, -0.7854F, 0.0F));

        PartDefinition torso_r2 = bone14.addOrReplaceChild("torso_r2", CubeListBuilder.create().texOffs(112, 0).addBox(-2.0F, -26.8F, 5.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(-1.0F, 14.8F, -2.0F, 0.0F, 0.7854F, 0.0F));

        PartDefinition torso_r3 = bone14.addOrReplaceChild("torso_r3", CubeListBuilder.create().texOffs(104, 106).addBox(-2.0F, -26.8F, -7.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(-1.0F, 14.8F, 2.0F, 0.0F, -0.7854F, 0.0F));

        PartDefinition torso_r4 = bone14.addOrReplaceChild("torso_r4", CubeListBuilder.create().texOffs(80, 106).addBox(-2.0F, -26.8F, -7.0F, 4.0F, 36.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(1.0F, 14.8F, 2.0F, 0.0F, 0.7854F, 0.0F));

        PartDefinition bone15 = torso.addOrReplaceChild("bone15", CubeListBuilder.create().texOffs(24, 131).addBox(-2.0F, -12.0F, -8.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F))
        .texOffs(60, 132).addBox(-2.0F, -12.0F, 6.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offset(0.0F, 8.0F, 0.0F));

        PartDefinition torso_r5 = bone15.addOrReplaceChild("torso_r5", CubeListBuilder.create().texOffs(128, 132).addBox(-2.0F, -26.8F, 5.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(-3.0F, 14.8F, 1.0F, 0.0F, -0.7854F, 0.0F));

        PartDefinition torso_r6 = bone15.addOrReplaceChild("torso_r6", CubeListBuilder.create().texOffs(48, 132).addBox(-2.0F, -26.8F, 5.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(3.0F, 14.8F, 1.0F, 0.0F, 0.7854F, 0.0F));

        PartDefinition torso_r7 = bone15.addOrReplaceChild("torso_r7", CubeListBuilder.create().texOffs(36, 131).addBox(-2.0F, -26.8F, -7.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(4.0F, 14.8F, 0.0F, 0.0F, -0.7854F, 0.0F));

        PartDefinition torso_r8 = bone15.addOrReplaceChild("torso_r8", CubeListBuilder.create().texOffs(12, 131).addBox(-2.0F, -26.8F, -7.0F, 4.0F, 19.0F, 2.0F, new CubeDeformation(0.6F)), PartPose.offsetAndRotation(-3.0F, 14.8F, 0.0F, 0.0F, 0.7854F, 0.0F));

        PartDefinition rightArm = body.addOrReplaceChild("rightArm", CubeListBuilder.create(), PartPose.offset(-12.0833F, -20.4722F, -0.1972F));

        PartDefinition armorRightArm = rightArm.addOrReplaceChild("armorRightArm", CubeListBuilder.create(), PartPose.offset(14.0833F, 10.4722F, 0.1972F));

        PartDefinition itemBone = rightArm.addOrReplaceChild("itemBone", CubeListBuilder.create(), PartPose.offsetAndRotation(15.0833F, 18.4722F, 0.1972F, 0.6981F, 0.0F, 0.0F));

        PartDefinition bone2 = rightArm.addOrReplaceChild("bone2", CubeListBuilder.create().texOffs(120, 74).mirror().addBox(-15.75F, -1.5833F, -1.4083F, 16.0F, 4.0F, 4.0F, new CubeDeformation(0.55F)).mirror(false), PartPose.offsetAndRotation(0.8333F, -1.9445F, -0.3945F, 0.0F, 0.0F, -0.6545F));

        PartDefinition bone4 = bone2.addOrReplaceChild("bone4", CubeListBuilder.create().texOffs(56, 0).mirror().addBox(-18.5F, -1.1667F, -4.8167F, 16.0F, 8.0F, 12.0F, new CubeDeformation(0.7F)).mirror(false)
        .texOffs(0, 42).mirror().addBox(-18.5F, -2.1667F, -4.8167F, 22.0F, 2.0F, 12.0F, new CubeDeformation(1.0F)).mirror(false), PartPose.offsetAndRotation(-14.25F, -0.4167F, -0.5917F, 0.0F, 0.0F, -0.5236F));

        PartDefinition bone5 = bone4.addOrReplaceChild("bone5", CubeListBuilder.create(), PartPose.offsetAndRotation(-19.0F, 1.8333F, -2.8167F, 0.0F, 0.0F, -0.6109F));

        PartDefinition armorRightArm_r1 = bone5.addOrReplaceChild("armorRightArm_r1", CubeListBuilder.create().texOffs(124, 15).mirror().addBox(-7.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)).mirror(false), PartPose.offsetAndRotation(-7.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0436F));

        PartDefinition bone6 = bone4.addOrReplaceChild("bone6", CubeListBuilder.create().texOffs(124, 20).mirror().addBox(-14.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)).mirror(false), PartPose.offsetAndRotation(-19.0F, 1.8333F, 1.1833F, 0.0F, 0.0F, -0.9163F));

        PartDefinition bone7 = bone4.addOrReplaceChild("bone7", CubeListBuilder.create().texOffs(124, 25).mirror().addBox(-14.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)).mirror(false), PartPose.offsetAndRotation(-19.0F, 1.8333F, 5.6833F, 0.0F, 0.0F, -1.309F));

        PartDefinition bone16 = bone4.addOrReplaceChild("bone16", CubeListBuilder.create().texOffs(124, 30).mirror().addBox(-14.5F, -1.0F, -2.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)).mirror(false), PartPose.offsetAndRotation(-11.0F, 3.8333F, -6.9167F, 0.0F, 0.0F, -0.6109F));

        PartDefinition leftArm = body.addOrReplaceChild("leftArm", CubeListBuilder.create(), PartPose.offset(12.0F, -21.0F, 0.0F));

        PartDefinition armorLeftArm = leftArm.addOrReplaceChild("armorLeftArm", CubeListBuilder.create(), PartPose.offset(0.0F, -1.0F, 0.0F));

        PartDefinition bone3 = armorLeftArm.addOrReplaceChild("bone3", CubeListBuilder.create(), PartPose.offset(17.0F, 4.0F, 0.0F));

        PartDefinition bone8 = leftArm.addOrReplaceChild("bone8", CubeListBuilder.create().texOffs(120, 74).addBox(-0.25F, -1.5833F, -1.4083F, 16.0F, 4.0F, 4.0F, new CubeDeformation(0.55F)), PartPose.offsetAndRotation(-0.75F, -1.4167F, -0.5917F, 0.0F, 0.0F, 0.6545F));

        PartDefinition bone9 = bone8.addOrReplaceChild("bone9", CubeListBuilder.create().texOffs(56, 0).addBox(2.5F, -1.1667F, -4.8167F, 16.0F, 8.0F, 12.0F, new CubeDeformation(0.7F))
        .texOffs(0, 42).addBox(-3.5F, -2.1667F, -4.8167F, 22.0F, 2.0F, 12.0F, new CubeDeformation(1.0F)), PartPose.offsetAndRotation(14.25F, -0.4167F, -0.5917F, 0.0F, 0.0F, 0.5236F));

        PartDefinition bone10 = bone9.addOrReplaceChild("bone10", CubeListBuilder.create(), PartPose.offsetAndRotation(19.0F, 1.8333F, -2.8167F, 0.0F, 0.0F, 0.6109F));

        PartDefinition armorLeftArm_r1 = bone10.addOrReplaceChild("armorLeftArm_r1", CubeListBuilder.create().texOffs(124, 15).addBox(-7.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)), PartPose.offsetAndRotation(7.0F, 0.0F, 0.0F, 0.0F, 0.0F, -0.0436F));

        PartDefinition bone11 = bone9.addOrReplaceChild("bone11", CubeListBuilder.create().texOffs(124, 20).addBox(-0.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)), PartPose.offsetAndRotation(19.0F, 1.8333F, 1.1833F, 0.0F, 0.0F, 0.9163F));

        PartDefinition bone12 = bone9.addOrReplaceChild("bone12", CubeListBuilder.create().texOffs(124, 25).addBox(-0.5F, -1.0F, -1.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)), PartPose.offsetAndRotation(19.0F, 1.8333F, 5.6833F, 0.0F, 0.0F, 1.309F));

        PartDefinition bone13 = bone9.addOrReplaceChild("bone13", CubeListBuilder.create().texOffs(124, 30).addBox(-0.5F, -1.0F, -2.5F, 15.0F, 2.0F, 3.0F, new CubeDeformation(0.75F)), PartPose.offsetAndRotation(11.0F, 3.8333F, -6.9167F, 0.0F, 0.0F, 0.6109F));

        PartDefinition rightLeg = body.addOrReplaceChild("rightLeg", CubeListBuilder.create(), PartPose.offset(-2.0F, 0.0F, 0.0F));

        PartDefinition armorRightBoot = rightLeg.addOrReplaceChild("armorRightBoot", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition armorRightLeg = rightLeg.addOrReplaceChild("armorRightLeg", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition leftLeg = body.addOrReplaceChild("leftLeg", CubeListBuilder.create(), PartPose.offset(2.0F, 0.0F, 0.0F));

        PartDefinition armorLeftBoot = leftLeg.addOrReplaceChild("armorLeftBoot", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition armorLeftLeg = leftLeg.addOrReplaceChild("armorLeftLeg", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-6.0F, -25.0F, -8.0F, 12.0F, 12.0F, 16.0F, new CubeDeformation(0.0F))
        .texOffs(52, 119).addBox(2.0F, -17.0F, -11.0F, 5.0F, 5.0F, 8.0F, new CubeDeformation(0.0F))
        .texOffs(128, 106).addBox(-7.0F, -17.0F, -11.0F, 5.0F, 5.0F, 8.0F, new CubeDeformation(0.0F))
        .texOffs(68, 41).addBox(2.0F, -27.0F, -11.0F, 5.0F, 5.0F, 8.0F, new CubeDeformation(0.0F))
        .texOffs(128, 119).addBox(-7.0F, -27.0F, -11.0F, 5.0F, 5.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -12.0F, 0.0F));

        PartDefinition head_r1 = head.addOrReplaceChild("head_r1", CubeListBuilder.create().texOffs(80, 77).addBox(4.0F, 33.0F, -4.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(-0.1F))
        .texOffs(68, 20).addBox(4.0F, 23.0F, -4.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(-0.1F)), PartPose.offsetAndRotation(-1.0F, -50.0F, -4.0F, 0.0F, 0.2618F, 0.0F));

        PartDefinition head_r2 = head.addOrReplaceChild("head_r2", CubeListBuilder.create().texOffs(96, 41).addBox(-2.0F, -2.5F, -8.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(0.0F))
        .texOffs(0, 97).addBox(7.8F, -2.5F, -8.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-4.8308F, -12.5F, -1.6892F, -0.2793F, 0.0F, 0.0F));

        PartDefinition head_r3 = head.addOrReplaceChild("head_r3", CubeListBuilder.create().texOffs(40, 98).addBox(-8.0F, 33.0F, -4.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(-0.1F))
        .texOffs(56, 56).addBox(-8.0F, 23.0F, -4.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(-0.1F)), PartPose.offsetAndRotation(1.0F, -50.0F, -4.0F, 0.0F, -0.2618F, 0.0F));

        PartDefinition head_r4 = head.addOrReplaceChild("head_r4", CubeListBuilder.create().texOffs(40, 77).addBox(-2.0F, -2.5F, -8.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(0.0F))
        .texOffs(0, 76).addBox(-11.8F, -2.5F, -8.0F, 4.0F, 5.0F, 16.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(4.9692F, -26.5F, -1.6892F, 0.2793F, 0.0F, 0.0F));

        PartDefinition armorHead = head.addOrReplaceChild("armorHead", CubeListBuilder.create().texOffs(120, 82).addBox(-17.0F, -2.0F, -1.0F, 18.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offset(0.0F, -18.0F, 0.0F));

        PartDefinition cube_r1 = armorHead.addOrReplaceChild("cube_r1", CubeListBuilder.create().texOffs(80, 102).addBox(-22.5F, -1.0F, -1.0F, 23.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 3.1416F, 0.0F, 2.1817F));

        PartDefinition cube_r2 = armorHead.addOrReplaceChild("cube_r2", CubeListBuilder.create().texOffs(80, 98).addBox(-22.5F, -1.0F, -1.0F, 23.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 3.1416F, 0.0F, 2.6616F));

        PartDefinition cube_r3 = armorHead.addOrReplaceChild("cube_r3", CubeListBuilder.create().texOffs(120, 86).addBox(-17.5F, -1.0F, -1.0F, 18.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 3.1416F, 0.0F, -3.1416F));

        PartDefinition cube_r4 = armorHead.addOrReplaceChild("cube_r4", CubeListBuilder.create().texOffs(96, 70).addBox(-22.5F, -1.0F, -1.0F, 23.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 0.0021F, -0.02F, 1.5704F));

        PartDefinition cube_r5 = armorHead.addOrReplaceChild("cube_r5", CubeListBuilder.create().texOffs(96, 66).addBox(-22.5F, -1.0F, -1.0F, 23.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 0.0132F, -0.0152F, 0.9594F));

        PartDefinition cube_r6 = armorHead.addOrReplaceChild("cube_r6", CubeListBuilder.create().texOffs(96, 62).addBox(-22.5F, -1.0F, -1.0F, 23.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 0.0187F, -0.0074F, 0.4795F));

        PartDefinition cube_r7 = armorHead.addOrReplaceChild("cube_r7", CubeListBuilder.create().texOffs(12, 127).addBox(-15.5F, -1.0F, -1.0F, 16.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 0.0F, 0.0F, -2.7489F));

        PartDefinition cube_r8 = armorHead.addOrReplaceChild("cube_r8", CubeListBuilder.create().texOffs(124, 35).addBox(-15.5F, -1.0F, -1.0F, 16.0F, 2.0F, 2.0F, new CubeDeformation(0.5F)), PartPose.offsetAndRotation(0.5F, -1.0F, 0.0F, 0.0F, 0.0F, -0.3927F));

        return LayerDefinition.create(meshdefinition, 256, 256);
    }

    @Override
    public void setupAnim(
            PhoenixGuardianEntity entity,
            float limbSwing,
            float limbSwingAmount,
            float ageInTicks,
            float netHeadYaw,
            float headPitch) {
        rootPart.getAllParts().forEach(ModelPart::resetPose);
        PhoenixGuardianRenderState state = new PhoenixGuardianRenderState();
        state.ageInTicks = ageInTicks;
        state.walkAnimationPos = limbSwing;
        state.walkAnimationSpeed = limbSwingAmount;
        state.yRot = netHeadYaw;
        state.xRot = headPitch;
        state.phase = entity.getPhase();
        state.phaseProgress = entity.getPhaseProgress(ageInTicks - entity.tickCount);
        state.rebirth = entity.getRebirthProgress(ageInTicks - entity.tickCount);
        state.risen = entity.hasRisen();
        state.attackTime = attackTime;
        state.hurtTime = Mth.clamp(entity.hurtTime / 10.0F, 0.0F, 1.0F);

        float hover = Mth.sin(state.ageInTicks * 0.045F);
        float drift = Mth.clamp(state.walkAnimationSpeed, 0.0F, 1.0F);
        float stride = Mth.cos(state.walkAnimationPos * 0.5F) * drift;

        // Legless: the whole body floats, and the wings carry the walk cycle
        // that legs would otherwise sell.
        body.y += hover * 1.4F - drift * 0.8F;

        head.yRot += state.yRot * (float) (Math.PI / 180.0);
        head.xRot += state.xRot * (float) (Math.PI / 180.0);
        armorHead.yRot += state.ageInTicks * 0.03F;

        torso.xRot += drift * 0.14F;
        torso.zRot += stride * 0.05F;
        bone14.zRot += stride * 0.09F + hover * 0.02F;
        bone15.zRot -= stride * 0.07F + hover * 0.03F;

        // Wing beat. The upper bone leads and the big section trails by a
        // quarter cycle, so the fan opens outward instead of moving as a slab.
        float beatSpeed = 0.09F + drift * 0.22F;
        float beat = Mth.sin(state.ageInTicks * beatSpeed);
        float trail = Mth.sin(state.ageInTicks * beatSpeed - 1.5708F);
        float spread = 0.10F + drift * 0.35F;

        rightArm.zRot -= beat * spread;
        leftArm.zRot += beat * spread;
        bone2.zRot -= trail * spread * 0.6F;
        bone8.zRot += trail * spread * 0.6F;
        bone4.zRot -= trail * spread * 0.35F;
        bone9.zRot += trail * spread * 0.35F;

        // Phase overlays. Each is a single sculpted pose scaled by its own
        // progress, so a phase that ends early eases out rather than snapping.
        float p = Mth.clamp(state.phaseProgress, 0.0F, 1.0F);
        switch (state.phase) {
            case CHARGE -> {
                // Wings fan wide and the body rears back: the telegraph.
                float fan = Mth.sin(p * (float) Math.PI * 0.5F);
                rightArm.zRot -= fan * 1.05F;
                leftArm.zRot += fan * 1.05F;
                bone4.zRot -= fan * 0.55F;
                bone9.zRot += fan * 0.55F;
                torso.xRot -= fan * 0.35F;
                body.y += fan * 2.5F;
            }
            case DASH -> {
                // Swept back and pitched into the charge.
                rightArm.zRot += 0.65F;
                leftArm.zRot -= 0.65F;
                rightArm.yRot += 0.5F;
                leftArm.yRot -= 0.5F;
                torso.xRot += 0.45F;
                body.y += 1.5F;
            }
            case STRIKE -> {
                // Both wing-arms slam down and across.
                float swing = Mth.sin(p * (float) Math.PI);
                rightArm.zRot += swing * 1.35F;
                leftArm.zRot -= swing * 1.35F;
                bone2.xRot -= swing * 0.8F;
                bone8.xRot -= swing * 0.8F;
                torso.xRot += swing * 0.3F;
            }
            case EMBER_BURST -> {
                // Thrown wide open and arched back around the detonation.
                float burst = Mth.sin(p * (float) Math.PI);
                rightArm.zRot -= burst * 1.5F;
                leftArm.zRot += burst * 1.5F;
                bone4.zRot -= burst * 0.9F;
                bone9.zRot += burst * 0.9F;
                torso.xRot -= burst * 0.6F;
                head.xRot -= burst * 0.5F;
                body.y += burst * 4.0F;
            }
            default -> {
            }
        }

        // Rebirth: the Curator draws itself inward, then flares back open.
        if (state.rebirth > 0.0F) {
            float curl = Mth.sin(state.rebirth * (float) Math.PI);
            rightArm.zRot += curl * 0.9F;
            leftArm.zRot -= curl * 0.9F;
            torso.xRot += curl * 0.7F;
            head.xRot += curl * 0.6F;
            body.y -= curl * 3.0F;
        }

        float swipe = Mth.sin(state.attackTime * (float) Math.PI);
        bone2.xRot -= swipe * 0.9F;
        bone8.xRot -= swipe * 0.9F;

        if (state.hurtTime > 0.0F) {
            torso.zRot += state.hurtTime * 0.12F;
            head.zRot -= state.hurtTime * 0.09F;
        }
    }

    @Override
    public void renderToBuffer(
            PoseStack poseStack,
            VertexConsumer vertexConsumer,
            int packedLight,
            int packedOverlay,
            int color) {
        rootPart.render(poseStack, vertexConsumer, packedLight, packedOverlay, color);
    }
}
